### ISSUE TITLE
Update Esprima version to v1.2.1

### ISSUE THREAD

**Issue by shellscape** [ariya/grunt-jsvalidate#11]
grunt-jsvalidate is currently using Esprima v1.0.4. That version lacks quite a few additions to Esprima which support ES6 syntax (and many, many fixes). We've started to use the Node 11 branch and can no longer use grunt-jsvalidate as part of our build process because it's using an older version of Esprima.

It would be great to get grunt-jsvalidate updated to use the latest version of Esprima.

**Comment by ariya** [comment]
Is there an example where grunt-jsvalidate currently fails?
Also, Esprima stable release with ES6 support is not available yet.

**Comment by shellscape** [comment]
It fails on any generator functions. I looked into the source tree and the commit for supporting generator functions looks like it's made it into the last version.

Even so, grunt-jsvalidate is using a version of Esprima that's two full minor versions behind. That alone is worth updating for.

**Comment by ariya** [comment]
As I mentioned already, many ES6 support in Esprima is still in an experimental branch, and not stable.

**Comment by ariya** [comment]
For some more info: https://groups.google.com/d/msg/esprima/hQO3-Hk8WRw/2fD2qI-now4J. And yes, I plan to bump it to Esprima 2.0 once it is available.

**Comment by shellscape** [comment]
6 months later, Esprima 2.0 isn't close to being released. Sadly, we're moving on from this project.

**Comment by michaelBenin** [comment]
Can we reopen this?
