### ISSUE TITLE
Not work with grunt 0.4.1

### ISSUE THREAD

**Issue by rottmann** [ariya/grunt-jsvalidate#4]
grunt 0.4.1
grunt-jsvalidate 0.2.0
(Node 0.8x and 0.10.1)

``` sh
Running "jsvalidate:files" (jsvalidate) task
Warning: Cannot read property 'src' of undefined Use --force to continue.
```

``` sh
jsvalidate: {
  files: ['app/**/*.js']
}
```

**Comment by m13** [comment]
You can change in the file ./tasks/jsvalidate.js 
from "grunt.file.expand(this.files.orig).forEach(function (filepath) {"
to "grunt.file.expand(this.files[0].orig).forEach(function (filepath) {"

It works... but I'll be waiting for a better solution :)

**Comment by ariya** [comment]
Fixed now. grunt-jsvalidate 0.2.1 package should have the fix.
