### ISSUE TITLE
Feature request: only output failures?

### ISSUE THREAD

**Issue by xzyfer** [ariya/grunt-jsvalidate#6]
The current output can be very noisy in automated systems like watch task, or ci servers.

```
Running "jsvalidate:files" (jsvalidate) task
Validating htdocs/static/js/foo.js  OK
Validating htdocs/static/js/bar.js  OK
Validating htdocs/static/js/baz.js  OK
```

It'd be great to be able only show failures as opposed to all files being tested. Something similar to what grunt-contrib-jshint does.

```
Running "jshint:all" (jshint) task
>> 3 files lint free.
```

**Comment by michaelBenin** [comment]
+1

**Comment by michaelBenin** [comment]
This can be closed now.
